version: 2

references:

  get_git_commit: &get_git_commit
    run:
      name: Get git revision from the git SHA1 using github API
      command: |
        curl --silent https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commits/${CIRCLE_SHA1} \
        | jq .sha | sed s/\"//g  >~/SVNREV

  git_checkout: &git_checkout
    run:
      name: Checkout from the github
      command: >
        git clone https://github.com/vscosta/cudd.git &&
        git clone https://github.com/vscosta/doxygen-yap.git &&
        git clone https://github.com/chair300/yap-6.3.git

  sm_build_cudd_linux: &sm_build_cudd_linux
    run:
      name: build cudd for linux
      command: |
        ls -la &&
        cd ~/cudd &&
        mkdir /artefacts &&
        mkdir inst &&
        ./configure --prefix=inst --enable-shared --enable-obj --enable-dddmp &&
        make -j2 install &&
        cd inst && tar czf /artefacts/cudd-linux-x86_64-shared.vcosta.tar.gz &&
        cd .. && rm -fr inst

  sm_distfile: &sm_distfile
    run:
      name: Creating src.tar.gz
      command: |
        ls -la &&
        cd smartmontools &&
        ls -la &&
        cd smartmontools &&
        ./autogen.sh --force &&
        mkdir build && cd build &&
        ../configure &&
        make dist && tar -tvzf smartmontools-7.2.tar.gz &&
        mkdir /artefacts &&
        mv smartmontools-7.2.tar.gz /artefacts/smartmontools.src.tar.gz

  sm_compile_linux: &sm_compile_linux
    run:
      name: Creating static x86_64 linux binaries
      command: |
        BUILD_INFO='"(CircleCI)"' &&
        mkdir ~/build && cd ~/build &&
        tar -xzf /artefacts/smartmontools.src.tar.gz &&
        cd smartmontools-7.2 && mkdir build && cd build &&
        ../configure LDFLAGS="-static" && make -j2 BUILD_INFO="$BUILD_INFO" && make check &&
        mkdir inst && make DESTDIR="$(pwd)/inst" install &&
        (cd inst && tar czf "/artefacts/smartmontools-linux-x86_64-static-7.2.tar.gz" *) &&
        rm -rf ~/build

  sm_compile_linux32: &sm_compile_linux32
    run:
      name: Creating static i386 linux binaries
      command: |
        SM_VER=`cat ~/SM_VER` && SVNREV=`cat ~/SVNREV` &&
        BUILD_INFO='"(CircleCI)"' &&
        mkdir ~/build && cd ~/build &&
        tar -xzf /artefacts/smartmontools-${SM_VER}-r${SVNREV}.src.tar.gz &&
        cd smartmontools-${SM_VER} && mkdir build && cd build &&
        ../configure CC="gcc -m32" CXX="g++ -m32" LDFLAGS="-static" &&
        make -j2 BUILD_INFO="$BUILD_INFO" && make check &&
        mkdir inst && make DESTDIR="$(pwd)/inst" install &&
        (cd inst && tar czf "/artefacts/smartmontools-linux-i386-static-${SM_VER}-r${SVNREV}.tar.gz" *) &&
        rm -rf ~/build

  sm_compile_linux_clang: &sm_compile_linux_clang
    run:
      name: Creating static x86_64 linux binaries and Clang Static Analyzer report
      command: |
        BUILD_INFO='"(CircleCI)"' &&
        mkdir ~/build && cd ~/build &&
        tar -xzf /artefacts/smartmontools.src.tar.gz &&
        cd smartmontools-7.2 && mkdir build && cd build &&
        ../configure CC=clang CXX=clang++ LDFLAGS="-static" &&
        HTMLDIR="smartmontools-linux-clang-analyzer-7.2" &&
        CHECKERS="
          optin.portability.UnixAPI optin.cplusplus.VirtualCall
          nullability.NullableDereferenced nullability.NullablePassedToNonnull
          nullability.NullableReturnedFromNonnull
          security.FloatLoopCounter security.insecureAPI.strcpy
          valist.CopyToSelf valist.Uninitialized valist.Unterminated
        " &&
        scan-build --use-cc clang --use-c++ clang++ -o $HTMLDIR \
            `for x in $CHECKERS; do echo -enable-checker $x; done` \
          make -j2 BUILD_INFO="$BUILD_INFO" && make check &&
        mkdir inst && make DESTDIR="$(pwd)/inst" install &&
        (cd inst && tar czf "/artefacts/smartmontools-linux-x86_64-static-clang-7.2.tar.gz" *) &&
        if ls -d $HTMLDIR/* >/dev/null 2>/dev/null; then
          tar czf "/artefacts/$HTMLDIR.tar.gz" $HTMLDIR ;
        fi &&
        rm -rf ~/build

  sm_compile_win: &sm_compile_win
    run:
      name: Creating Windows installer
      command: |
        SM_VER=`cat ~/SM_VER` && SVNREV=`cat ~/SVNREV` &&
        BUILD_INFO='"(CircleCI)"' &&
        mkdir ~/build && cd ~/build &&
        tar -xzf /artefacts/smartmontools-${SM_VER}-r${SVNREV}.src.tar.gz &&
        cd smartmontools-${SM_VER} && mkdir build && cd build &&
        ../configure build_alias=$(../config.guess) host_alias=i686-w64-mingw32 &&
        make -j2 BUILD_INFO="$BUILD_INFO" && make distdir-win32 &&
        cd .. && mkdir build64 && cd build64 &&
        ../configure build_alias=$(../config.guess) host_alias=x86_64-w64-mingw32 &&
        make -j2 BUILD_INFO="$BUILD_INFO" && make distdir-win32 &&
        cd ../build &&
        dest="smartmontools-win32-setup-${SM_VER}-r${SVNREV}.exe" &&
        make BUILD_INFO="$BUILD_INFO" builddir_win64=../build64 distinst_win32="$dest" installer-win32 &&
        mv "$dest" /artefacts &&
        rm -rf ~/build

  sm_compile_darwin: &sm_compile_darwin
    run:
      name: Creating Darwin image
      command: |
        export PATH=/usr/osxcross/bin/:$PATH &&
        BUILD_INFO='"(CircleCI)"' &&
        SM_VER=`cat ~/SM_VER` && SVNREV=`cat ~/SVNREV` &&
        mkdir ~/build && cd ~/build &&
        tar -xzf /artefacts/smartmontools-${SM_VER}-r${SVNREV}.src.tar.gz &&
        cd smartmontools-${SM_VER} && mkdir build && cd build &&
        ../configure build_alias=$(../config.guess) host_alias=x86_64-apple-darwin14 \
          'CC=o64-clang' 'CXX=o64-clang++' 'CFLAGS=-arch i386 -arch x86_64' \
          'CXXFLAGS=-arch i386 -arch x86_64' '--sysconfdir=/private/etc' &&
        make -j2 BUILD_INFO="$BUILD_INFO" &&
        make pkg_darwin=smartmontools-${SM_VER}-r${SVNREV}.pkg dmg_darwin=smartmontools-${SM_VER}-r${SVNREV}.dmg install-darwin &&
        mv smartmontools-${SM_VER}-r${SVNREV}.dmg "/artefacts/" &&
        rm -rf ~/build

  sm_compile_freebsd11: &sm_compile_freebsd11
    run:
      name: Creating static FreeBSD-11.3/amd64 binaries
      command: |
        SM_VER=`cat ~/SM_VER` && SVNREV=`cat ~/SVNREV` &&
        BUILD_INFO='"(CircleCI)"' &&
        mkdir ~/build && cd ~/build &&
        tar -xzf /artefacts/smartmontools-${SM_VER}-r${SVNREV}.src.tar.gz &&
        cd smartmontools-${SM_VER} && mkdir build && cd build &&
        TARGET="-target x86_64-unknown-freebsd11 --sysroot=/opt/cross-freebsd-11/" &&
        ../configure CC="clang $TARGET" CXX="clang++ $TARGET" LDFLAGS="-static" --host=x86_64-pc-freebsd11 &&
        make -j2 BUILD_INFO="$BUILD_INFO" &&
        mkdir inst && make DESTDIR="$(pwd)/inst" install &&
        (cd inst && tar czf "/artefacts/smartmontools-freebsd11.3-amd64-static-${SM_VER}-r${SVNREV}.tar.gz" *) &&
        rm -rf ~/build

  sm_compile_freebsd12: &sm_compile_freebsd12
    run:
      name: Creating static FreeBSD-12.1/amd64 binaries
      command: |
        BUILD_INFO='"(CircleCI)"' &&
        mkdir ~/build && cd ~/build &&
        tar -xzf /artefacts/smartmontools.src.tar.gz &&
        cd smartmontools-7.2 && mkdir build && cd build &&
        TARGET="-target x86_64-unknown-freebsd12 --sysroot=/opt/cross-freebsd-12/" &&
        ../configure CC="clang $TARGET" CXX="clang++ $TARGET" LDFLAGS="-static" --host=x86_64-pc-freebsd12 &&
        make -j2 BUILD_INFO="$BUILD_INFO" &&
        mkdir inst && make DESTDIR="$(pwd)/inst" install &&
        (cd inst && tar czf "/artefacts/smartmontools-freebsd12.1-amd64-static.tar.gz" *) &&
        rm -rf ~/build

  sm_run_cppcheck: &sm_run_cppcheck
    run:
      name: Creating Cppcheck report
      command: |
        SM_VER=`cat ~/SM_VER` && SVNREV=`cat ~/SVNREV` &&
        mkdir ~/build && cd ~/build &&
        tar -xzf /artefacts/smartmontools-${SM_VER}-r${SVNREV}.src.tar.gz &&
        cd smartmontools-${SM_VER} &&
        ./cppcheck.sh -j2 -q | tee /artefacts/smartmontools-cppcheck-${SM_VER}-r${SVNREV}.txt &&
        rm -rf ~/build

  sm_compute_hashes: &sm_compute_hashes
    run:
      name: Compute SHA256 hashes of all generated files
      command: |
        SM_VER=`cat ~/SM_VER` && SVNREV=`cat ~/SVNREV` &&
        cd /artefacts &&
        sha256sum smartmontools-* > smartmontools-${SM_VER}-r${SVNREV}.all.sha256 &&
        cat smartmontools-${SM_VER}-r${SVNREV}.all.sha256

  centos_deps: &centos_deps
    run:
      name: Install dependencies on CentOS.
      command: |
        yum update -y
        yum install -y gcc git make gcc-c++ automake

jobs:

  test_ubuntu_latest:
    docker:
      - image: chair300/yap-build-server:latest
    working_directory: ~/
    steps:
      - *get_git_commit
      - *git_checkout
      - *sm_build_cudd_linux
#      - *sm_distfile
#      - *sm_compile_freebsd12
#      - *sm_distfile
#      - *sm_compile_linux
#      - *sm_compile_linux32
#      - *sm_compile_win
#      - *sm_compile_darwin
#      - *sm_compile_freebsd11
#      - *sm_compile_freebsd12
#      - *sm_compile_linux_clang
#      - *sm_run_cppcheck
#      - *sm_compute_hashes

      - store_artifacts:
          path: /artefacts
          destination: builds

  test_centos_latest:
    docker:
      - image: centos:latest
    working_directory: ~/smartmontools
    steps:
      - *centos_deps
      - checkout
      # - *sm_compile
      # - *sm_install

workflows:

  version: 2
  test-matrix:
    jobs:
      - test_ubuntu_latest
##      - test_centos_latest

notify:
  webhooks:
    - url: https://builds-ci.smartmontools.org/hook.php
